app/forum/models.py
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 07 14:41:30 2014

@author: Gouthaman Balaraman
"""

from app import db
from datetime import datetime

question_followers = db.Table('question_followers',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('question_id', db.Integer(), db.ForeignKey('question.id'))
    )

    
question_topics = db.Table('question_topics',
        db.Column('topic_id', db.Integer(), db.ForeignKey('topic.id')),
        db.Column('question_id', db.Integer(), db.ForeignKey('question.id'))    
    )
    
    
topic_followers = db.Table('topic_followers',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('topic_id', db.Integer(), db.ForeignKey('topic.id'))
    )
    

class Question(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    question = db.Column(db.String(127), unique=True)
    description = db.Column(db.String(255))
    topics = db.relationship("Topic", secondary=question_topics, 
                        backref=db.backref("questions_tagged", lazy='dynamic'))
    anonymous = db.Column(db.Boolean)
    created_at = db.Column(db.DateTime())
    lastedit_at = db.Column(db.DateTime())
    # relationship to user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', 
                         backref=db.backref('questions_asked',lazy='dynamic'))
    # relationship to votes
    votes = db.relationship('QuestionVotes',backref='question')
    # followers
    followers = db.relationship('User', secondary=question_followers,
                        backref=db.backref('questions_followed', lazy='dynamic'))
    def __init__ (self, question, description, topics, anonymous=False):
        self.question = question
        self.description = description
        self.topics = topics
        self.created_at = datetime.now()
        self.lastedit_at = datetime.now()
        self.anonymous = anonymous
        #self.tags = tags
    

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text)
    anonymous = db.Column(db.Boolean)
    created_at = db.Column(db.DateTime())
    lastedit_at = db.Column(db.DateTime())
    # relationship to user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref=db.backref('answers', lazy='dynamic'))
    user_desc = db.Column(db.String(63))
    # relationship to question
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'))
    question = db.relationship('Question', 
                               backref=db.backref('answers',lazy='dynamic'))
    # relationship to votes
    votes = db.relationship('AnswerVotes', backref='answer')

    
class QuestionVotes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    upvote = db.Column(db.Boolean) #if false, its a downvote
    anonymous = db.Column(db.Boolean)
    # link to user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref=db.backref('q_votes',lazy='dynamic')) 
    user_desc = db.Column(db.String(63))
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'))
    
    
class AnswerVotes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    upvote = db.Column(db.Boolean) #if false, its a downvote
    anonymous = db.Column(db.Boolean)
    # link to user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref=db.backref('a_votes',lazy='dynamic'))    
    answer_id = db.Column(db.Integer, db.ForeignKey('answer.id'))
    
    
class Topic(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), unique=True)
    description = db.Column(db.String(255))
    followers = db.relationship('User', secondary=topic_followers, 
                                backref = db.backref('topics',lazy='dynamic') )
    
    

app/forum/forms.py
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 10 03:58:21 2014

@author: Gouthaman Balaraman
"""

from flask.ext.wtf import Form
from wtforms import StringField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired

class QuestionForm(Form):
    question = StringField('Question', validators=[DataRequired()])
    description = StringField('Description', widget=TextArea())
    tags = StringField("Tags", validators=[DataRequired()])

app/__init__.py
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 05 08:50:01 2014

@author: Gouthaman Balaraman
"""
import os
from flask import Flask, render_template, request, redirect
from flask.ext.security import login_required

BASEDIR = os.path.abspath(os.path.join(os.path.dirname(__file__),'..'))
TEMPLATE_FOLDER = os.path.join(BASEDIR,"templates")
STATIC_FOLDER   = os.path.join(BASEDIR,"static")

def create_app():
    app = Flask(__name__,
                template_folder = os.path.join(BASEDIR,"templates"),
                static_folder   = os.path.join(BASEDIR,"static"),
                static_url_path = "/static")
    
    app.config.from_object('app.config.DebugConfig')
    from app.forum.views import forum_bp
    app.register_blueprint(forum_bp)
    from flask.ext.sqlalchemy import SQLAlchemy
    db = SQLAlchemy(app)
    return app, db

app, db = create_app()

# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

@app.before_request 
def remove_trailing_slash(): 
    if request.path != '/' and request.path.endswith('/'): 
        return redirect(request.path[:-1]) 

# default views
@app.route('/')
@login_required
def home():
    return render_template('index.html')

app/forum/__init__.py
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 07 14:41:23 2014

@author: Gouthaman Balaraman
"""

app/forum/views.py
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 08 12:39:12 2014

@author: Gouthaman Balaraman
"""

from flask import Blueprint, request, render_template
from flask.ext.security.core import current_user
from flask.ext.security import login_required
from app import TEMPLATE_FOLDER, STATIC_FOLDER
from forms import QuestionForm



forum_bp = Blueprint('forum',__name__,
                    template_folder = TEMPLATE_FOLDER,
                    static_folder = STATIC_FOLDER,
                    url_prefix = "/forum")
                    



@forum_bp.route('/addq', methods=["GET", "POST"])
@login_required
def add_question():
    form = QuestionForm()
    if request.method == 'GET':
        
        return render_template("forum/add_question.html", form=form)
    else:
        try:
            from app import db
            from models import Question, Topic
            #if current_user.is_authenticated():
            topic_list = [request.form['tags']]
            topics = [ ]
            for topic_name in topic_list:
                t = Topic.query.filter_by(name=topic_name).all()
                print t
                if t != []:
                    topics.append(t[0])
            
            question = Question(request.form['question'], request.form['description'], 
                                topics)
            print request.form
            db.session.add(question)
            db.session.commit()
                
        except Exception as e:
            print str(e)
        finally:
            return
            return render_template("index.html")

templates/_macros.html
{% macro render_field_with_errors(field) %}
  <p>
    <dt>{{ field.label }} </dt>
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  </p>
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

{% macro render_field_safe(field) %}
  {{ field(**kwargs)|safe }}
{% endmacro %}

templates/_menu.html
{% if security.registerable or security.recoverable or security.confirmabled %}
<h2>Menu</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}">Login</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}">Register</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">Forgot password</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">Confirm account</a></li>
  {% endif %}
</ul>
{% endif %}

templates/base.html
<!DOCTYPE html>
<html lang="en" ng-app="exampleApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--link rel="shortcut icon" href="../../assets/ico/favicon.ico"-->

    <title>{% block title %}{{ config.SITENAME }} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="static/css/bootstrap.readable.min.css">
    <!-- Custom styles for this template -->
    <link href="static/css/starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">{{config.SITENAME}}</a>
        </div>
        <div class="collapse navbar-collapse pull-right">
          <ul class="nav navbar-nav">
            Test
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container" role="main">
        <div >
        <br><br>
            <div class="row">
                <div class="col-md-3">
                    {% block sidecontent %} {% endblock %}    
                </div>
                <div class="col-md-9">
                    {% block maincontent %} {% endblock %}    
                </div>
            
            </div>
        </div>
    </div><!-- /.container -->
    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
    <script src="static/js/angularapp.js"></script>
  </body>
</html>

templates/forum/add_question.html
{% extends 'index.html' %}

{% block maincontent %}
{% from "_macros.html" import render_field_with_errors, render_field_safe %}
<form class="form-horizontal" method="POST" action="{{ url_for('forum.add_question') }}">
{{ form.hidden_tag() }}

<fieldset>

<!-- Form Name -->
<legend>Add Question</legend>
    <div class="form-group">
        <label class="col-md-2 control-label" for="questioninput">Question</label>  
        <div class="col-md-7">
        {{ render_field_safe( form.question, maxlength="127", placeholder="Gist of your question",id="questioninput", class="form-control input-md", required="" )}}
        </div>
    </div>
    <!-- Textarea -->
    <div class="form-group">
      <label class="col-md-2 control-label" for="textarea">Description</label>
      <div class="col-md-7">                     
        {{ render_field_safe( form.description, rows=5,placeholder="Description or context for your question",
            id="questiondesc", class="form-control")}}
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-2 control-label" for="taginput">Tags</label>  
      <div class="col-md-7">
          {{ render_field_safe( form.tags, placeholder="Comma separated tags",
            id="taginput", class="form-control input-md", required="" )}}          
      </div>
    </div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-2 control-label" for="singlebutton"></label>
  <div class="col-md-7">
    <button id="singlebutton" name="singlebutton" class="btn btn-primary">Submit</button>
  </div>
</div>

</fieldset>
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block sidecontent%}
    <a href="/forum/addq">Add Question </a>
{% endblock %}

{% block maincontent %}
Hello World!
{%endblock %}

templates/security/login_user.html
{% extends 'base.html' %}
{% block title %} {{config.SITENAME}}-Login {% endblock %}
{% from "_macros.html" import render_field_with_errors, render_field %}
{% block maincontent %}
    <h2>Login</h2>
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        <div class="control-group">
            <div class="controls">
            {{ render_field_with_errors( login_user_form.email,size=40 )}}<br>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
            {{ render_field_with_errors( login_user_form.password,size=40 )}}<br>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn btn-success">SignIn</button>
            </div>
        </div>
        
    </form>
{% endblock %}

templates/security/register.html
{% extends 'base.html' %}

{% block title %} {{ title}}{% endblock %}

{% block maincontent %}
{% if error %}
    {{error }}
{% endif %}

{% from "appmacros.html" import render_field %}
  <form action="{{request.path}}" method="post" class="form-horizontal">
       {{form.hidden_tag()}}
    <h2>Register </h2>
    <div class="control-group">
        <div class="controls">
           {{ render_field( form.username,size=40 )}}<br>
        </div>
    </div>
 
    <div class="control-group">
        <div class="controls">
           {{ render_field( form.password,size=40 )}}<br>
        </div>
    </div>
 
    <div class="control-group">
        <div class="controls">
           {{ render_field( form.email,size=40 )}}<br>
        </div>
    </div>
 
    <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-success">Signup</button>
        </div>
    </div>
  </form>
{% endblock %}